### ISSUE TITLE
How to find the location of cell click

### ISSUE THREAD

**Issue by jbeuria** [iamyuu/gridjs-svelte#13]
<Grid
    {columns}
	sort
	search
	pagination={{ enabled: true, limit: 30 }}
    data={orderdata}
    on:cellClick={handleClick}
/>

How do I determine which cell has been clicked?

**Comment by kevinJread** [comment]
function handleClick(e) {
  console.log(e);
}

the event (e) will have the cell info in the detail section

**Comment by jbeuria** [comment]
Thanks Kevin, unfortunately it shows undefined for me. Although I can locate the column through id, the row index is nowhere to be found!

**Comment by jbeuria** [comment]
thank you

**Comment by iamyuu** [comment]
thanks for your help @kevinJread! feel free to re-open or open new issues if you have
