### ISSUE TITLE
How add plugins?

### ISSUE THREAD

**Issue by jbeuria** [iamyuu/gridjs-svelte#14]
Can someone help me how to add plugins as described in https://gridjs.io/docs/plugins/writing-plugin

I want to add an extra button on header and an customised footer.

**Comment by jbeuria** [comment]
I found one REPL https://svelte.dev/repl/9a066ccf55f54173bf5c6c8042142566?version=3.42.0 

But it does not seem to render. Kindly check and suggest

**Comment by iamyuu** [comment]
now it's working, sorry for delay response
