### ISSUE TITLE
Style for grid

### ISSUE THREAD

**Issue by Audhut** [iamyuu/gridjs-svelte#18]
How do i assign custom style classes to the grid?

can you provide an example?

**Comment by iamyuu** [comment]
You can read it on [Grid.js](gridjs.io) docs

- [custom style](https://gridjs.io/docs/config/style)
- [custom class](https://gridjs.io/docs/config/className)

and this the example usage with gridjs-svelte:
https://svelte.dev/repl/d6fffbcd8ce0409c8bdb4a7c2e7df63c
