### ISSUE TITLE
How to include links in the grid

### ISSUE THREAD

**Issue by Audhut** [iamyuu/gridjs-svelte#19]
iam trying to include  links inot the grid. but howevwer its not working.

refer the https://svelte.dev/repl/e9efbc965bca48c5911b748247237875?version=3.46.4

**Comment by iamyuu** [comment]
You forgot to add more items to `data`

Here the example to add row button
https://svelte.dev/repl/80eca12417414c7eabc79756c5a8f464?version=3.46.4
