### ISSUE TITLE
Please add on:hover event

### ISSUE THREAD

**Issue by eric-naguras** [iamyuu/gridjs-svelte#21]
Great work!

I'd like to have a custom hover event so I can respond when a row is hovered over.

Thanks.

**Comment by iamyuu** [comment]
Hey, thanks for the suggestion but this package is for integration Grid.js with Svelte. So for future requests, you may need to [open new issues](https://github.com/grid-js/gridjs/issues/new?assignees=&labels=&template=feature_request.md&title=) on the core package first, after that you can re-open these issues or open the PR.

**Comment by eric-naguras** [comment]
Ok, thanks.
