### ISSUE TITLE
how to add plugin?

### ISSUE THREAD

**Issue by timeshift92** [iamyuu/gridjs-svelte#3]

**Comment by iamyuu** [comment]
I'm not sure this is the best approach or not, but it's work.

Follow this instruction:
1. [Write some plugin](https://gridjs.io/docs/plugin/writing-plugin).
2. [Get Grid.js instance](https://gridjs.io/docs/integrations/svelte#how-to-get-instance).
3. Add the plugin to Grid.js instance using [`grid.plugin.add`](https://gridjs.io/docs/plugin/basics#adding-a-plugin).
4. the last step we need to re-render so the plugin can show up, we can use [`grid.forceRender`](https://gridjs.io/docs/examples/force-render).

[Try it out in the browser](https://svelte.dev/repl/9a066ccf55f54173bf5c6c8042142566?version=3.37.0)

**Comment by iamyuu** [comment]
I'll add to the docs (at least on readme file) soon, thanks for opening issues.
