### ISSUE TITLE
rowClick working?

### ISSUE THREAD

**Issue by larrym** [iamyuu/gridjs-svelte#5]
I can't get the rowClick event to fire. What am I doing wrong? Nothing on the console.

    const handleRowClick = (event) => {
    	console.log('triggered click');
    };

    ...
    <div class="grid">
    	{#await promise}
    		<p>Loading ...</p>
    	{:then data}
    		<Grid {data} {columns} {style} on:rowClick={handleRowClick} />
    	{/await}
    </div>

**Comment by iamyuu** [comment]
Actually, I do not yet add any event dispatcher right now (I'll add it soon). For now, you can check the example at https://github.com/iamyuu/gridjs-svelte/issues/4#issuecomment-834303046.

**Comment by iamyuu** [comment]
added on [v1.1.0](https://github.com/iamyuu/gridjs-svelte/releases/tag/1.1.0), thanks for creating issues.
