### ISSUE TITLE
Table does not update if config changes.

### ISSUE THREAD

**Issue by pmkroeker** [iamyuu/gridjs-svelte#8]
You an change any of the config options in a Grid, but the component does not call on gridjs to force render with the updates. This leads to some hacky methods (#1) to update the rendered table.

Unfortunately I am using snowpackjs with svelte, so its not quite as easy as adding some code into the node_modules folder to fix this, but I feel like adding:

```js
$: instance.updateConfig({
    from,
    data,
    columns,
    server,
    search,
    sort,
    pagination,
    language,
    width,
    height,
    autoWidth,
    fixedHeader,
    style,
    className,
    resizable,
  }).forceRender();
```

into `gridjs.svelte` would update the instance config whenever any of the attributes change.

**Comment by iamyuu** [comment]
Feel free to open PR

**Comment by mhkeller** [comment]
This still doesn't seem to work. Here's an example updating the data variable and it doesn't re-render the grid: https://svelte.dev/repl/1d5a553b102141b58dd42efc68063d55?version=3.46.4
